# Copyright (c) 2025-2026 Meridian Innovation. All rights reserved.
from typing import TYPE_CHECKING, Literal, cast

from senxor.consts import SENXOR_TYPE2FRAME_SHAPE

if TYPE_CHECKING:
    from senxor.regmap.core import SenxorFieldsManager, SenxorRegistersManager


class SenxorHelperMixin:
    """The Mixin class for Senxor. Provide a set of helper methods for Senxor. Do not use this class directly."""

    def __init__(self):
        self.fields: SenxorFieldsManager
        self.regs: SenxorRegistersManager

    def get_shape(self) -> tuple[int, int]:
        """Get the frame shape(height, width) of the senxor.

        Returns
        -------
        tuple[int, int]
            The frame shape(height, width) of the senxor.

        """
        # Although the frame shape depends on the senxor type, but the internal implementation of `read` method
        # do not rely on this method.

        senxor_type = self.fields.SENXOR_TYPE.get()
        frame_shape = SENXOR_TYPE2FRAME_SHAPE.get(senxor_type, None)
        if frame_shape is None:
            raise ValueError(
                f"Unknown senxor type: {senxor_type}, please report this issue to the developer.",
                "https://github.com/meridianinnovation/pysenxor-lite/issues",
            )
        return frame_shape

    def disable_all_filters(self):
        """Disable all filters inside the senxor.

        This method will set the following filters to disabled:

        - STARK
        - MMS KXMS
        - MMS RA
        - Median
        - Temporal

        See related fields .help attribute to get more information about the filters.
        """
        self.set_stark_enable(False)
        self.set_mms_kxms_enable(False)
        self.set_mms_ra_enable(False)
        self.set_median_enable(False)
        self.set_temporal_enable(False)

    def get_filters_status(self) -> dict[Literal["stark", "mms_kxms", "mms_ra", "median", "temporal"], bool]:
        """Get the status of all filters.

        Returns
        -------
        dict[str, bool]
            The status of all filters.
            Available keys:

            - stark
            - mms_kxms
            - mms_ra
            - median
            - temporal

            The value is True if the filter is available in current device and enabled.

        """
        return {
            "stark": self.get_stark_enable(),
            "mms_kxms": self.get_mms_kxms_enable(),
            "mms_ra": self.get_mms_ra_enable(),
            "median": self.get_median_enable(),
            "temporal": self.get_temporal_enable(),
        }

    def get_fw_version(self) -> str:
        """Get the firmware version string.

        The firmware version is a string of the format "major.minor.build".

        Returns
        -------
        str
            The firmware version string.

        Examples
        --------
        >>> senxor.get_fw_version()
        "4.5.12"

        """
        major = self.fields.FW_VERSION_MAJOR.get()
        minor = self.fields.FW_VERSION_MINOR.get()
        build = self.fields.FW_VERSION_BUILD.get()
        return f"{major}.{minor}.{build}"

    def get_frame_rate_divider(self) -> int:
        """Get the frame rate divider.

        The frame rate divider is determined by the `FRAME_RATE_DIVIDER` field.

        The frame rate is calculated as: `frame_rate = FPS_MAX / FRAME_RATE_DIVIDER`.
        When `FRAME_RATE_DIVIDER` is 0, the maximum frame rate (FPS_MAX) is used.

        Note: The actual maximum frame rate depends on device performance and is typically around 30 fps.
        Due to variations in frame transmission, avoid using this calculated value for precise frame rate measurement.
        Instead, calculate the actual frame rate from the timestamps of received frames.


        Returns
        -------
        int
            The frame rate divider.

        """
        return self.fields.FRAME_RATE_DIVIDER.get()

    def set_frame_rate_divider(self, divider: int):
        """Set the frame rate divider.

        The frame rate divider is determined by the `FRAME_RATE_DIVIDER` field.
        The frame rate is calculated as: `frame_rate = FPS_MAX / FRAME_RATE_DIVIDER`.
        When `FRAME_RATE_DIVIDER` is 0, the maximum frame rate (FPS_MAX) is used.

        Note: The actual maximum frame rate depends on device performance and is typically around 30 fps.

        Parameters
        ----------
        divider : int
            The frame rate divider to set.

        """
        self.fields.FRAME_RATE_DIVIDER.set(divider)

    def get_module_gain(self) -> str:
        """Get the module gain setting.

        The module gain defines the common amplification of the signal generated by each pixel
        in the SenXor array. Increased amplification improves signal to noise ratio but limits
        the range of scene temperatures that can be reported.

        Returns
        -------
        str
            The module gain setting as a string. Possible values:

            - "1.0" (default, maximum gain)
            - "auto" (automatic gain selection: 1.0, 0.5, or 0.25 based on input signal)
            - "0.25" (quarter gain)
            - "0.5" (half gain)

        """
        return cast("str", self.fields.MODULE_GAIN.display)

    def set_module_gain(self, gain: int):
        """Set the module gain setting.

        Parameters
        ----------
        gain : int
            The module gain setting as an integer. Possible values:

            - 0: 1.0 (default, maximum gain)
            - 1: auto (automatic gain selection: 1.0, 0.5, or 0.25 based on input signal)
            - 2: 0.25 (quarter gain)
            - 3: 0.5 (half gain)

        """
        self.fields.MODULE_GAIN.set(gain)

    def get_senxor_type(self) -> str:
        """Get the senxor type.

        Returns
        -------
        str
            The senxor type.

        """
        return cast("str", self.fields.SENXOR_TYPE.display)

    def get_module_type(self) -> str:
        """Get the module type.

        Returns
        -------
        str
            The module type.

        """
        return cast("str", self.fields.MODULE_TYPE.display)

    def get_mcu_type(self) -> str:
        """Get the MCU type.

        Returns
        -------
        str
            The MCU type.

        """
        return cast("str", self.fields.MCU_TYPE.display)

    def get_production_year(self) -> int:
        """Get the production year.

        Returns
        -------
        int
            The production year.

        """
        return self.fields.PRODUCTION_YEAR.get() + 2000

    def get_production_week(self) -> int:
        """Get the production week.

        Returns
        -------
        int
            The production week.

        """
        return self.fields.PRODUCTION_WEEK.get()

    def get_manuf_location(self) -> int:
        """Get the manufacturing location.

        Returns
        -------
        int
            The manufacturing location.

        """
        return self.fields.MANUF_LOCATION.get()

    def get_serial_number(self) -> int:
        """Get the serial number.

        Returns
        -------
        int
            The serial number as an integer.

        """
        res = (
            self.fields.SERIAL_NUMBER_0.get() << 16
            | self.fields.SERIAL_NUMBER_1.get() << 8
            | self.fields.SERIAL_NUMBER_2.get()
        )
        return res

    def get_sn(self) -> str:
        """Get the SN code string in hex format.

        The SN code is a hex string of 12 characters, the format is:
        `YYWWLLSSSSSS`, where:

        - `YY` is the production year (from 2000 to 2099).
        - `WW` is the production week.
        - `LL` is the manufacturing location.
        - `SSSSSS` is the serial number (from 000000 to 999999).

        Returns
        -------
        str
            The SN code string in hex format.

        """
        production_year = self.fields.PRODUCTION_YEAR.get()
        production_week = self.fields.PRODUCTION_WEEK.get()
        manuf_location = self.fields.MANUF_LOCATION.get()
        serial_number = self.get_serial_number()
        return f"{production_year:02X}{production_week:02X}{manuf_location:02X}{serial_number:06X}"

    def get_module_name(self) -> Literal["Cougar", "Panther", "Cheetah"]:
        """Get the module name.

        Returns
        -------
        str
            The module name. Possible values:

            - "Cougar" (62x80)
            - "Panther" (120x160)
            - "Cheetah" (50x50)

        """
        frame_shape = self.get_shape()

        if frame_shape == (62, 80):
            return "Cougar"
        elif frame_shape == (120, 160):
            return "Panther"
        elif frame_shape == (50, 50):
            return "Cheetah"
        else:
            raise ValueError(
                "Unknown frame shape, please report this issue to the developer.",
                "https://github.com/meridianinnovation/pysenxor-lite/issues",
            )

    def get_sensitivity(self) -> float:
        """Get the sensitivity.

        Multiplicative factor applied to the temperature readout of every pixel, allowing correction of the sensitivity.

        Returns
        -------
        float
            The sensitivity.

        """
        value = self.fields.CORR_FACTOR.get()
        return round(value * 0.01, 2)

    def set_sensitivity(self, value: float):
        """Set the sensitivity.

        Multiplicative factor applied to the temperature readout of every pixel, allowing correction of the sensitivity.

        Parameters
        ----------
        value : float
            The sensitivity to set.

        """
        field_value = int(value * 100)
        self.fields.CORR_FACTOR.set(field_value)

    def get_emissivity(self) -> float:
        """Get the emissivity.

        Emissivity value (percent) to be used in the conversion of raw data captured from SenXor to the temperature data
        that is readout through the SPI interface.
        The reset value reflects the emissivity of the black body source used for factory calibration of the camera
        module.
        If the target object is known to have a different emissivity, programming the correct value will lead to an
        accurate readout of the absolute temperature.

        Returns
        -------
        float
            The emissivity.

        """
        value = self.fields.EMISSIVITY.get()
        return round(value * 0.01, 2)

    def set_emissivity(self, value: float):
        """Set the emissivity.

        Emissivity value (percent) to be used in the conversion of raw data captured from SenXor to the temperature data
        that is readout through the SPI interface.
        The reset value reflects the emissivity of the black body source used for factory calibration of the camera
        module.
        If the target object is known to have a different emissivity, programming the correct value will lead to an
        accurate readout of the absolute temperature.

        Parameters
        ----------
        value : float
            The emissivity to set.

        """
        field_value = int(value * 100)
        self.fields.EMISSIVITY.set(field_value)

    def get_offset(self) -> float:
        """Get the offset correction.

        Temperature offset correction. This specifies a temperature offset applied to every pixel in the data frame.

        Units: K(or °C)
        Range: -12.8 K to +12.7 K

        Returns
        -------
        float
            The offset correction.

        """
        uint8 = self.fields.OFFSET.get()
        int8 = uint8 if uint8 < 128 else uint8 - 256
        value = round(int8 * 0.1, 1)
        return value

    def set_offset(self, value: float):
        """Set the offset correction.

        Temperature offset correction. This specifies a temperature offset applied to every pixel in the data frame.

        Units: K(or °C)
        Range: -12.8 K to +12.7 K

        Parameters
        ----------
        value : float
            The offset correction to set.

        """
        int8 = int(value * 10)
        uint8 = int8 if int8 >= 0 else int8 + 256
        self.fields.OFFSET.set(uint8)

    def get_otf(self) -> float:
        """Get the OTF.

        A multiplicative factor applied to each pixel's value before the frame is output.
        This is used to correct for size-of-source optical phenomena.

        Resolution: 0.01
        Range: -1.28 to +1.27

        Returns
        -------
        float
            The OTF.

        """
        uint8 = self.fields.OTF.get()
        int8 = uint8 if uint8 < 128 else uint8 - 256
        value = round(int8 * 0.01, 2)
        return value

    def set_otf(self, value: float):
        """Set the OTF.

        A multiplicative factor applied to each pixel's value before the frame is output.
        This is used to correct for size-of-source optical phenomena.

        Resolution: 0.01
        Range: -1.28 to +1.27

        Parameters
        ----------
        value : float
            The OTF to set.

        """
        int8 = int(value * 100)
        uint8 = int8 if int8 >= 0 else int8 + 256
        self.fields.OTF.set(uint8)

    def get_stark_enable(self) -> bool:
        """Get the STARK enable flag.

        Returns
        -------
        bool
            Whether the STARK filter is available in current device and enabled.

        """
        return self.fields.STARK_ENABLE.available and self.fields.STARK_ENABLE.get() == 1

    def set_stark_enable(self, enabled: bool):
        """Set the STARK enable flag.

        Parameters
        ----------
        enabled : bool
            The STARK enable flag to set.

        """
        if not self.fields.STARK_ENABLE.available:
            return
        self.fields.STARK_ENABLE.set(1 if enabled else 0)

    def get_mms_kxms_enable(self) -> bool:
        """Get the MMS KXMS enable flag.

        Returns
        -------
        bool
            Whether the MMS KXMS filter is available in current device and enabled.

        """
        return self.fields.MMS_KXMS.available and self.fields.MMS_KXMS.get() == 1

    def set_mms_kxms_enable(self, enabled: bool):
        """Set the MMS KXMS enable flag.

        Parameters
        ----------
        enabled : bool
            The MMS KXMS enable flag to set.

        """
        if not self.fields.MMS_KXMS.available:
            return
        self.fields.MMS_KXMS.set(1 if enabled else 0)

    def get_mms_ra_enable(self) -> bool:
        """Get the MMS RA enable flag.

        Returns
        -------
        bool
            Whether the MMS RA filter is available in current device and enabled.

        """
        return self.fields.MMS_RA.available and self.fields.MMS_RA.get() == 1

    def set_mms_ra_enable(self, enabled: bool):
        """Set the MMS RA enable flag.

        Parameters
        ----------
        enabled : bool
            The MMS RA enable flag to set.

        """
        if not self.fields.MMS_RA.available:
            return
        self.fields.MMS_RA.set(1 if enabled else 0)

    def get_median_enable(self) -> bool:
        """Get the median enable flag.

        Returns
        -------
        bool
            Whether the median filter is available in current device and enabled.

        """
        return self.fields.MEDIAN_ENABLE.available and self.fields.MEDIAN_ENABLE.get() == 1

    def set_median_enable(self, enabled: bool):
        """Set the median enable flag.

        Parameters
        ----------
        enabled : bool
            The median enable flag to set.

        """
        if not self.fields.MEDIAN_ENABLE.available:
            return
        self.fields.MEDIAN_ENABLE.set(1 if enabled else 0)

    def get_temporal_enable(self) -> bool:
        """Get the temporal enable flag.

        Returns
        -------
        bool
            Whether the temporal filter is available in current device and enabled.

        """
        return self.fields.TEMPORAL_ENABLE.available and self.fields.TEMPORAL_ENABLE.get() == 1

    def set_temporal_enable(self, enabled: bool):
        """Set the temporal enable flag.

        Parameters
        ----------
        enabled : bool
            The temporal enable flag to set.

        """
        if not self.fields.TEMPORAL_ENABLE.available:
            return
        self.fields.TEMPORAL_ENABLE.set(1 if enabled else 0)

    def get_adc_enabled(self) -> bool:
        """Whether the raw ADC data is enabled.

        This flag is determined by the `ADC_ENABLE` field.
        When it is 1, the read method will return the raw ADC data.

        Returns
        -------
        bool
            Whether the raw ADC data is enabled.

        """
        return self.fields.ADC_ENABLE.get() == 1

    def set_adc_enabled(self, enabled: bool):
        """Set the raw ADC data enabled flag.

        If the raw ADC data is enabled, the read method will return the raw ADC data.
        If you are not sure whether you need to use the raw ADC data, do not modify this value.

        Parameters
        ----------
        enabled : bool
            Whether to enable the raw ADC data.

        """
        self.fields.ADC_ENABLE.set(1 if enabled else 0)
